version: "3.9"

services:
  web:
    build: .
    command: python3 main.py
    volumes:
      - media_data:/usr/src/app/media
    ports:
      - "127.0.0.1:${DOCKER_OUT_PORT}:${PORT}"
volumes:
  media_data:
